version: '3'

services:
  my_marvin:
    container_name: my_marvin_original
    build: .
    environment:
        - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
        - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
        - USER_CHOCOLATEEN_PASSWORD=lol
        - USER_VAUGIE_G_PASSWORD=vvv
        - USER_I_DONT_KNOW_PASSWORD=idkman
        - USER_NASSO_PASSWORD=nassnass
    volumes:
        - ./my_marvin.yml:/var/jenkins_home/casc_configs
    ports:
        - 8080:8080